# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

#Google login credentials
GOOGLE_FORECAST_ID: "253429751107-g9mvl8edvrkaikc6250tkfahgerqou4t.apps.googleusercontent.com"
GOOGLE_FORECAST_SECRET: "fmZ6Puazu53YyCx2oQ6T_9ah"

#Facebook login credentials
FACEBOOK_FORECAST_ID: "363657240505998"
FACEBOOK_FORECAST_SECRET: "a0a638f590aebd4610e2c17dc06de721"